theme: osuny
_merge: deep
params:
  logo:
    footer: "/assets/images/LogoMaquinas2.svg"
    header: "/assets/images/LogoMaquinas2.svg"
  search:
    active: false
  summary:
    position: hero
cdnkey: https://osuny-1b4da.kxcdn.com/
cookie_banner:
  enable: true
  blank: true
  page: https://gdpr.eu/cookies/
